### ISSUE TITLE
Can't get past login screen

### ISSUE THREAD

**Issue by betterthanever2** [Receipt-Wrangler/receipt-wrangler-api#282]
I installed RW on Ubuntu. Here's my `compose` file:
```
services:
  api:
    image: noah231515/receipt-wrangler-api:latest
    container_name: receipt-wrangler-api
    restart: always
    command: ./api --env prod
    ports:
      - 50980:8081
    volumes:
      - ./data:/go/api/data
      - ./logs:/go/api/logs
    environment:
      - ENCRYPTION_KEY=encryptionKey
      - SECRET_KEY=secretKey
      - DB_USER=<user>
      - DB_PASSWORD=<pw>
      - DB_NAME=receipt_wrangler
      - DB_HOST=<db>
      - DB_PORT=<port>
      - DB_ENGINE=postgresql

  frontend:
    image: noah231515/receipt-wrangler-desktop:latest
    container_name: receipt-wrangler-frontend
    restart: always
    ports:
      - 50981:80
```
On top of this, I'm using Caddy for reverse proxy. 

After the install, I can get to login screen using IP address, but attempts to log in raise 405. When I use the https host name, I'm only getting empty page. 

What could be the issue?

**Comment by zzahkaboom24** [comment]
For me, the solution was to login through the proxy, not through the frontend.
I dont know if that would help you, but try using this `compose` file and going through the port defined in the proxy service instead (in your case, possibly 50982. I tried guessing what port you'd use):

```
services:
  api:
    image: noah231515/receipt-wrangler-api:latest
    container_name: receipt-wrangler-api
    restart: always
    command: ./api --env prod
    ports:
      - 50980:8081
    volumes:
      - ./data:/go/api/data
      - ./logs:/go/api/logs
    environment:
      - ENCRYPTION_KEY=encryptionKey
      - SECRET_KEY=secretKey
      - DB_USER=<user>
      - DB_PASSWORD=<pw>
      - DB_NAME=receipt_wrangler
      - DB_HOST=<db>
      - DB_PORT=<port>
      - DB_ENGINE=postgresql

  proxy:
    image: noah231515/receipt-wrangler-proxy:latest
    ports:
      - 50982:80
    depends_on:
      - api
      - frontend

  frontend:
    image: noah231515/receipt-wrangler-desktop:latest
    container_name: receipt-wrangler-frontend
    restart: always
    ports:
      - 50981:80
```
