### ISSUE TITLE
Cant find config.prod.json or any config file, that is

### ISSUE THREAD

**Issue by zzahkaboom24** [Receipt-Wrangler/receipt-wrangler-api#283]
Currently running on Docker with the following compose file, I even kept it at default for testing purposes, and I cant for the life of me find out where config.prod.json should be.
I am trying to run it with MariaDB (microservices) and I dont know why it wont show up. If I need to share more info, logs or whatever, I can do so.
All I could find were system changes to be stored was in my MariaDB container actually, however, I am unsure how to change stuff like "aiPoweredReceipts": true that I dont seem to find in the web ui

```
version: "3.5"
services:
  db:
    image: library/mariadb:10
    restart: always
    command: --sql-mode="ANSI_QUOTES"
    environment:
      - MYSQL_ROOT_PASSWORD=change_me2
      - MYSQL_USER=wrangler
      - MYSQL_PASSWORD=change_me
      - MYSQL_DATABASE=wrangler
    volumes:
      - ./mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 10s
      retries: 5

  proxy:
    image: noah231515/receipt-wrangler-proxy:latest
    ports:
      - 9082:80
    depends_on:
      - api
      - frontend

  api:
    image: noah231515/receipt-wrangler-api:latest
    restart: always
    working_dir: /go/api
    command: ./api --env prod
    ports:
      - 9080:8081
    volumes:
      - ./data:/go/api/data
      - ./logs:/go/api/logs
    environment:
      - ENCRYPTION_KEY=encryptionKey
      - SECRET_KEY=secretKey
      - DB_USER=wrangler
      - DB_PASSWORD=change_me
      - DB_NAME=wrangler
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ENGINE=mariadb
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: noah231515/receipt-wrangler-desktop:latest
    restart: always
    ports:
      - 9081:80
```
