### ISSUE TITLE
Support for `*_FILE` env variables

### ISSUE THREAD

**Issue by ryami333** [Receipt-Wrangler/receipt-wrangler-api#386]
I would like to request that Receipt Wrangler support configuration via `*_FILE` environment variables, such that we can leverage [Docker Secrets](https://docs.docker.com/compose/how-tos/use-secrets/) to pass sensitive  data, or at least support for specific configuration options that might be considered sensitive, eg. `DB_PASSWORD_FILE` and `REDIS_PASSWORD_FILE`.

This pattern has been implemented upstream in many popular services already (eg. [Postgres](https://hub.docker.com/_/postgres#:~:text=it%20into%20account.-,Docker%20Secrets,-As%20an%20alternative), [MariaDB](https://hub.docker.com/_/mariadb#:~:text=downgrade%20if%20needed.-,Secrets,-As%20an%20alternative)) already, so if this is implemented in Receipt Wrangler (or at least in the Receipt Wrangler Docker image) then this will enable the following:

```yml
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=wrangler
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=wrangler
    secrets:
      - POSTGRES_PASSWORD

  wrangler:
    image: noah231515/receipt-wrangler:latest
    environment:
      - DB_USER=wrangler
      - DB_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - DB_NAME=wrangler
    secrets:
      - POSTGRES_PASSWORD
secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt
```
